apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          env:
          - name: MAX_HEAP
            value: "800m"
          - name: MIN_HEAP
            value: "300m"
          resources:
            limits:
              memory: "6Gi"
              cpu: "1200m"
            requests:
              memory: "4Gi"
              cpu: "800m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-vol
              mountPath: /setup
      volumes:
        - name: nexus-vol
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: ClusterIP  
  ports:
    - port: 8081
      targetPort: 8081