# ExternalSecret for Homepage
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
  - secretKey: proxmox-password
    remoteRef:
      key: homepage/config
      property: proxmox_password
  - secretKey: argocd-token
    remoteRef:
      key: homepage/config
      property: argocd_token
  - secretKey: portainer-key
    remoteRef:
      key: homepage/config
      property: portainer_key
  - secretKey: grafana-password
    remoteRef:
      key: homepage/config
      property: grafana_password