apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-kustomize
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/DzwS/devops-projects.git
    targetRevision: HEAD
    path: cicd/argo/kustomize/environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true