apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: homepage
spec:
  provider:
    vault:
      server: "http://192.168.5.152:8200"
      path: "kv/org"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "homepage"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: homepage
type: Opaque
data:
  token: cm9vdA== # "root" 的 Base64 编码